name: Check changesets
on:
  pull_request:
    branches:
      - main

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0 # changesets can't see `main` branch on PRs for some reason
      
      - name: Check changesets
        run: npx changeset status --since origin/main