name: Check changesets
on: [pull_request]

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}  # changesets can't see `main` branch on PRs for some reason
          fetch-depth: 0                                # https://github.com/changesets/changesets/issues/517

      - name: Use yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.cache-numbers.outputs.cache-hit != 'true'
        run: yarn install --immutable
      
      - name: Check changesets
        run: yarn changeset status --since origin/main
