name: Check changesets
on: [pull_request]

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}  # changesets can't see `main` branch on PRs for some reason
          fetch-depth: 0                                # https://github.com/changesets/changesets/issues/517

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Restore yarn cache
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            '**/node_modules'
            '.yarn/install-state.gz'
          key: node-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable
      
      - name: Check changesets
        run: yarn changeset status --since origin/main
